### ISSUE TITLE
SIMBOLOGIA TIPO LINEA ADICIONAL

### ISSUE THREAD

**Issue by JamirGarro** [qgispe/discusiones#12]
![imagen_2021-07-13_141118](https://user-images.githubusercontent.com/86505835/125511219-6ebd97bf-a10c-4117-8d36-398f418ee1f5.png)
Como podria obtener ese tipo de simbologia, no me sale en mi QGIS por defecto.

**Comment by ambarja** [comment]
Hola @JamirGarro  las posibles soluciones estarán dentro de las discusiones :next_track_button: [click aquí](https://github.com/qgispe/discusiones/discussions/14)
