### ISSUE TITLE
¿Cómo podría reducir la visualización de las etiquetas de una capa?

### ISSUE THREAD

**Issue by hfsoriad** [qgispe/discusiones#4]
Hola a todos. Buenos días. 
Mi consulta se refiere para reducir el nombre de etiquetado de un capa. Por ejemplo, en el caso de quebradas (líneas celestes o azules), me gustaría que muestre solo uno o dos nombres por línea según el campo asignado, y no que se repite por varios nombres en todo su trayecto (tal como sucede con aquellos que están en círculo rojo). En este caso, estoy trabajando con un mapa en escala 1:1'500,000 en tamaño A0. Adjunto la imagen.

https://ibb.co/0cmZQFh

Estaré agradecido por su respuesta y gentileza.

Saludos,
Henry

**Comment by lefcgis** [comment]
Hola Henry. Se me ocurre que una opción es que limites el número de objeto a etiquetar (adjunto imagen). La otra es que lo limites a una escala determinada (como lo mencionas arriba) y vayas interactuando con las opciones de etiquetado.
![Captura de pantalla 2021-05-14 111527](https://user-images.githubusercontent.com/13573242/118299536-7d054400-b4a6-11eb-8e9f-c266e9873dc9.png)


Lucho.

**Comment by hfsoriad** [comment]
> Hola Henry. Se me ocurre que una opción es que limites el número de objeto a etiquetar (adjunto imagen). La otra es que lo limites a una escala determinada (como lo mencionas arriba) y vayas interactuando con las opciones de etiquetado.
> ![Captura de pantalla 2021-05-14 111527](https://user-images.githubusercontent.com/13573242/118299536-7d054400-b4a6-11eb-8e9f-c266e9873dc9.png)
> 
> Lucho.

**Comment by hfsoriad** [comment]
Hola @lefcgis.
Excelente. Me ha servido de mucho tu ayuda. 
Te agradezco mucho. 
Gracias. 
Henry

**Comment by lefcgis** [comment]
De nada, amigo. ¡A compartir y liberarnos!


L.
